use_frameworks!

platform :ios, '9.0'

target 'HomeModule_Example' do
  pod 'HomeModule', :path => '../'

  target 'HomeModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
